fix: oidc configure view for sentry 24.8.0
This currently errors out with
`ImportError: cannot import name 'ConfigureView' from 'sentry.auth.view'`
because of https://github.com/getsentry/sentry/commit/6ea317f564734cd216e85d8c7ba270ae4cc85b36